#!/bin/bash

# Scriptname
SCRIPT=$( basename "$0" )

# Scriptversion
VERSION="1.0"


# --help message
function usage
{
    local usageTxt=(
"Usage: $SCRIPT [options] <command> [arguments]"
""
"Command:"
"  reverse [string]                 Reverses the given string."
"  factors [n1] [n2] [n3] [n..]     Prints factorial of given numbers."
"  starwars                         Starts showing the Star Wars movies in ASCII."
""
"Options:"
"  --help, -h     Print help."
"  --version, -v  Print version."
    )

    printf "%s\n" "${usageTxt[@]}"
}



# Print when incorrect usage of script (unrecognized command/option etc)
function badUsage
{
    local message="$1"
    local txt=(
"For an overview of the command, execute:"
"$SCRIPT --help"
    )

    [[ $message ]] && printf "$message\n"

    printf "%s\n" "${txt[@]}"
}



# --version message
function version
{
    local txt=(
"$SCRIPT version $VERSION"
    )

    printf "%s\n" "${txt[@]}"
}



# Function for the reverse command.
function app-reverse
{
    echo $@|rev
}



# Function for the factors command.
function app-factors
{
    for x in $*
    do
        echo $(factor $x)
    done
}

function app-starwars
{
    telnet towel.blinkenlights.nl
}



# Process options
while (( $# ))
do
    case "$1" in

        --help | -h)
            usage
            exit 0
        ;;

        --version | -v)
            version
            exit 0
        ;;

        reverse         \
        | factors       \
        | starwars)
            command=$1
            shift
            app-$command $*
            exit 0
        ;;

        *)
            badUsage "Option/command not recognized."
            exit 1
        ;;

    esac
done

badUsage
exit 1
